# Generated by Django 4.1.5 on 2023-01-07 09:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='default.jpg', max_length=255, verbose_name='avatar'),
        ),
    ]
