# Generated by Django 4.1.5 on 2023-01-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='body',
        ),
    ]
