# Generated by Django 4.1.5 on 2023-01-07 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/images/default_ym3edb.jpg', upload_to='images/'),
        ),
    ]
